In [10]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [11]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

2021-09-27 14:39:24.007 
  command:

    streamlit run /Users/robertsarno/Documents/Summer_2021 /Udemy/Nerual_Networking/Artifitial-NN/ANN/lib/python3.9/site-packages/ipykernel_launcher.py [ARGUMENTS]


In [12]:
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# Preprocessing Stuff

le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')

X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [13]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
# Build ANN
###########
###########
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [15]:
# Train ANN
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
219/219 [==============================] - 1s 659us/step - loss: 0.5622 - accuracy: 0.7623
Epoch 2/100
219/219 [==============================] - 0s 648us/step - loss: 0.4718 - accuracy: 0.8081
Epoch 3/100
219/219 [==============================] - 0s 709us/step - loss: 0.4451 - accuracy: 0.8101
Epoch 4/100
219/219 [==============================] - 0s 745us/step - loss: 0.4335 - accuracy: 0.8103
Epoch 5/100
219/219 [==============================] - 0s 765us/step - loss: 0.4267 - accuracy: 0.8114
Epoch 6/100
219/219 [==============================] - 0s 835us/step - loss: 0.4210 - accuracy: 0.8156
Epoch 7/100
219/219 [==============================] - 0s 777us/step - loss: 0.4160 - accuracy: 0.8167
Epoch 8/100
219/219 [==============================] - 0s 722us/step - loss: 0.4113 - accuracy: 0.8197
Epoch 9/100
219/219 [==============================] - 0s 766us/step - loss: 0.4069 - accuracy: 0.8213
Epoch 10/100
219/219 [==============================] - 0s 671us/step - l

In [16]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)

print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [1 1]]


In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[2262  117]
 [ 306  315]]


0.859